In [1]:
import torch
from torch import nn
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import pandas as pd
pd.set_option('display.max_rows', 1000)

## 1.数据预处理

In [3]:
transform = transforms.ToTensor()
# 这个就是一个转换规则，意思转换成Tensor这个数据类型，因为读进来的是原始图片，要把他转换成tensor的数据类型

## 2. Download Training Set

In [4]:
train_data = datasets.FashionMNIST(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

In [5]:
test_data = datasets.FashionMNIST(
    root="./data",
    train=False,
    download=True,
    transform=transform
)

In [6]:
image, lable = train_data[1]
print(image)
print(lable)
# 所以这个dataset这个对象其实就是一个存了数据本身和lable的一个东西

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0039, 0.0000, 0.0000,
          0.0000, 0.0000, 0.1608, 0.7373, 0.4039, 0.2118, 0.1882, 0.1686,
          0.3412, 0.6588, 0.5216, 0.0627, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0039, 0.0000, 0.0000, 0.0000, 0.1922,
          0.5333, 0.8588, 0.8471, 0.8941, 0.9255, 1.0000, 1.0000, 1.0000,
          1.0000, 0.8510, 0.8431, 0.9961, 0.9059, 0.6275, 0.1765, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0549, 0.6902, 0.8706,
          0.8784, 0.8314, 0.7961, 0.7765, 0.7686, 0.7843, 0.8431, 0.8000,
          0.7922, 0.7882, 0.7882, 0.7882, 0.8196, 0.8549, 0.8784, 0.6431,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.7373, 0.8588, 0.7843,
          0.7765, 0.7922, 0.7765, 0.7804, 0.7804, 0.7882, 0.7686, 0.7765,
          0.7765, 0.7843, 0.7843, 0.7843, 0.7843, 0.7882,

In [7]:
# 创建dataloader
batch_size = 256

train_iter = DataLoader(
    train_data,
    batch_size=batch_size,
    shuffle=True
)

test_iter = DataLoader(
    test_data,
    batch_size=batch_size,
    shuffle=False
)
# 此时的train_iter变成了一个DataLoader对象

In [8]:
# 如果要查看里面的数据
X, y = next(iter(train_iter))
X
y
# 这样取出来的就是第一个第一个iter

tensor([[[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.2588, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.1882, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..

tensor([4, 4, 2, 7, 4, 5, 8, 5, 8, 8, 4, 0, 5, 0, 6, 5, 3, 3, 3, 7, 8, 6, 4, 8,
        3, 8, 0, 4, 3, 3, 6, 3, 8, 0, 1, 9, 0, 5, 2, 3, 8, 4, 1, 9, 8, 1, 9, 7,
        1, 0, 7, 7, 5, 2, 2, 9, 9, 2, 9, 3, 6, 8, 8, 5, 5, 3, 5, 0, 9, 7, 7, 4,
        6, 8, 4, 4, 6, 8, 0, 5, 1, 0, 6, 2, 1, 4, 7, 2, 3, 8, 2, 4, 9, 3, 7, 9,
        3, 3, 4, 7, 2, 7, 4, 1, 2, 5, 9, 3, 5, 8, 3, 8, 8, 9, 3, 2, 9, 6, 6, 1,
        6, 1, 1, 1, 6, 5, 1, 7, 0, 2, 9, 3, 2, 5, 0, 4, 1, 7, 5, 9, 9, 9, 8, 8,
        4, 6, 9, 8, 6, 6, 5, 2, 1, 8, 3, 9, 2, 8, 6, 3, 3, 2, 6, 0, 3, 8, 7, 5,
        2, 9, 3, 5, 9, 2, 7, 1, 7, 6, 1, 5, 3, 6, 5, 4, 6, 4, 8, 1, 1, 3, 0, 5,
        5, 5, 1, 9, 6, 8, 5, 0, 2, 5, 6, 3, 9, 5, 7, 2, 6, 5, 3, 1, 4, 4, 3, 9,
        9, 5, 5, 0, 5, 9, 3, 5, 6, 3, 3, 1, 5, 7, 6, 0, 9, 2, 2, 5, 9, 8, 2, 1,
        0, 3, 4, 3, 3, 0, 4, 7, 4, 6, 0, 6, 6, 6, 1, 3])

In [9]:
# model
net = nn.Sequential(
    nn.Flatten(), # 将一个28*28的单个对象展平成[1, 784]
    nn.Linear(784, 256), # 中间层，将784变成256个节点
    nn.ReLU(), # 添加一个非线性层
    nn.Linear(256, 10) # 输出层，讲中间层的256输出成10个分类结果
)

In [10]:
# Loss function
loss_fn = nn.CrossEntropyLoss()

In [11]:
# optimizer
optimizer = torch.optim.SGD(
    net.parameters(),
    lr = 0.1
)

In [12]:
net.parameters()
# 其实也就会获取w1, w2, b1, b2

<generator object Module.parameters at 0x30bf17a50>

In [13]:
# 训练函数

def train(net, train_iter, loss_fn, optimizer, epochs):
    for epoch in range(epochs):

        net.train() # 启动train模式

        for X, y in train_iter:
            y_hat = net(X) # 前向传播，根据输入给出预测值
            loss = loss_fn(y_hat, y)
            optimizer.zero_grad()
            loss.backward() # 反向传播
            optimizer.step() # 更新参数

In [14]:
# 测试函数

def test(net, test_iter):

    net.eval()

    correct  = 0
    total = 0

    with torch.no_grad(): # 意思不用计算梯度，节约资源

        for X, y in test_iter:
            y_hat = net(X)
            pred = y_hat.argmax(dim = 1)
            correct += (pred==y).sum().item() # item()是将tensor转换为可以累加的python数字
            total += y.size(0)

    return correct/total

In [15]:
# argmax函数使用案例，就是沿着每一个数据寻找概率最大的并且标记
test_1 = torch.tensor([[1, 2, 3],
                    [2, 3, 4]])
test_max = test_1.argmax(dim = 1)
test_max

tensor([2, 2])

In [16]:
y.size()
X.size()

torch.Size([256])

torch.Size([256, 1, 28, 28])

In [17]:
# 开始训练
train(net, train_iter, loss_fn, optimizer, epochs=10)

acc = test(net, test_iter)

print(acc)

0.8239
