In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import pandas as pd
pd.set_option('display.max_rows', 1000)

In [2]:
%matplotlib inline
import random
import torch
from d2l import torch as d2l

In [ ]:
X = torch.normal(2, 1, [3, 3])
X
X2 = torch.tensor([[1., 1., 1.], [2., 2., 2.], [3., 3., 3.]])
w = torch.tensor([1., 2., 1.])
b = torch.tensor([1., 2., 1.])
y = torch.matmul(X, w) + b
y
y = torch.matmul(X2, w) + b
y
y = X2 @ w + b
y

tensor([[2.4072, 2.4012, 2.2070],
        [3.3493, 1.7280, 3.1053],
        [3.1258, 0.6264, 1.6979]])

tensor([10.4166, 11.9106,  7.0765])

tensor([ 5., 10., 13.])

tensor([ 5., 10., 13.])

In [ ]:
X = torch.tensor([[1, 2], [3, 4]])
X
X.reshape(-1, 1)

tensor([[1, 2],
        [3, 4]])

tensor([[1],
        [2],
        [3],
        [4]])

In [ ]:
features.shape
lables.shape

torch.Size([20, 2])

torch.Size([20, 1])

In [ ]:
print('feature:', features[0], '\nlable:', lables[0])

feature: tensor([-0.0154,  1.2408]) 
lable: tensor([-3.1916])


In [ ]:
len(features)
features[[1, 2, 3]]

20

tensor([[-0.7146, -1.2985],
        [-2.1713,  0.4378],
        [-0.3152, -1.3879]])

In [3]:
def synthetic_data(w, b, num_examples):  #@save
    """生成y=Xw+b+噪声"""
    X = torch.normal(0, 1, (num_examples, len(w)))
    y = torch.matmul(X, w) + b
    y += torch.normal(0, 0.01, y.shape)
    return X, y.reshape((-1, 1))

In [4]:
def data_iter(batch_size, features, lables):
    num_examples = len(features)
    indices = list(range(num_examples))

    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        batch_indices = torch.tensor(
            indices[i:min(i + batch_size, num_examples)]
        )
        yield features[batch_indices], lables[batch_indices]


In [7]:
true_w = torch.tensor([2.1, 3.2])
true_b = -1

features, lables = synthetic_data(true_w, true_b, 27)
features
lables

tensor([[-0.4125,  0.1832],
        [-1.9593, -0.3827],
        [-0.8496, -1.2030],
        [-0.0299,  0.4957],
        [ 0.0821, -1.1216],
        [ 0.9028, -0.4648],
        [-1.4016,  0.0577],
        [ 1.2429, -0.8081],
        [-0.1890,  1.8517],
        [ 0.0226,  0.4463],
        [-0.5473,  0.0842],
        [ 1.5480,  0.0745],
        [-0.6103,  1.5969],
        [ 0.9648,  0.5596],
        [ 0.7006, -0.7940],
        [ 0.8745,  0.3244],
        [ 0.1815,  1.0274],
        [-0.5459,  0.9167],
        [ 0.7632,  0.2054],
        [ 0.4723, -0.1475],
        [-0.4765, -0.6397],
        [-2.5565,  1.2337],
        [-0.5748,  0.3398],
        [ 2.6003,  2.0089],
        [-1.9944,  0.0971],
        [ 0.5292, -2.8803],
        [-0.0488,  0.3472]])

tensor([[-1.2837e+00],
        [-6.3534e+00],
        [-6.6432e+00],
        [ 5.1286e-01],
        [-4.4172e+00],
        [-5.7750e-01],
        [-3.7554e+00],
        [-9.8784e-01],
        [ 4.5233e+00],
        [ 4.9962e-01],
        [-1.8835e+00],
        [ 2.4772e+00],
        [ 2.8306e+00],
        [ 2.8145e+00],
        [-2.0738e+00],
        [ 1.8597e+00],
        [ 2.6622e+00],
        [ 7.7849e-01],
        [ 1.2616e+00],
        [-4.9046e-01],
        [-4.0473e+00],
        [-2.4232e+00],
        [-1.1222e+00],
        [ 1.0877e+01],
        [-4.8548e+00],
        [-9.0997e+00],
        [ 5.1227e-03]])

In [8]:
batch_size = 5
i = 0

for X, y in data_iter(batch_size, features, lables):
    print(f"Batch{i}")
    i += 1
    print(X, '\n', y)
    

Batch0
tensor([[-0.5459,  0.9167],
        [-0.8496, -1.2030],
        [-2.5565,  1.2337],
        [ 0.7632,  0.2054],
        [ 0.8745,  0.3244]]) 
 tensor([[ 0.7785],
        [-6.6432],
        [-2.4232],
        [ 1.2616],
        [ 1.8597]])
Batch1
tensor([[-0.5748,  0.3398],
        [-1.9944,  0.0971],
        [ 0.9028, -0.4648],
        [ 0.0226,  0.4463],
        [-0.4125,  0.1832]]) 
 tensor([[-1.1222],
        [-4.8548],
        [-0.5775],
        [ 0.4996],
        [-1.2837]])
Batch2
tensor([[ 1.5480,  0.0745],
        [ 1.2429, -0.8081],
        [-0.4765, -0.6397],
        [-0.6103,  1.5969],
        [-1.9593, -0.3827]]) 
 tensor([[ 2.4772],
        [-0.9878],
        [-4.0473],
        [ 2.8306],
        [-6.3534]])
Batch3
tensor([[ 0.4723, -0.1475],
        [-0.5473,  0.0842],
        [ 0.0821, -1.1216],
        [ 0.1815,  1.0274],
        [ 0.5292, -2.8803]]) 
 tensor([[-0.4905],
        [-1.8835],
        [-4.4172],
        [ 2.6622],
        [-9.0997]])
Batch4
tensor([[

In [10]:
w = torch.normal(0, 0.01, size = (2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad = True)
w
b

tensor([[ 0.0003],
        [-0.0119]], requires_grad=True)

tensor([0.], requires_grad=True)

In [ ]:
def linreg(X, w, b):
    y = torch.matmul(X, w) + b
    return y

def squared_loss(y_hat, y):
    loss = ((y_hat - y) ** 2) / 2
    return loss

def sgd(params, lr, batch_size)