In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import pandas as pd
pd.set_option('display.max_rows', 1000)

In [2]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [21]:
true_w = torch.tensor([2, 0.1])
true_b = 1
features, lables = d2l.synthetic_data(true_w, true_b, 19)
features
lables

tensor([[-0.8330,  1.3084],
        [-0.8957,  0.3543],
        [-0.4510,  0.4578],
        [-0.5219, -0.8494],
        [ 0.9881,  2.3124],
        [-1.4265,  0.5725],
        [-0.4412, -0.0936],
        [-0.4842, -0.7460],
        [ 0.5799,  0.0231],
        [-1.7279, -2.0894],
        [-1.0675, -1.0780],
        [-0.6760, -0.0595],
        [-1.5275, -0.4477],
        [-0.1890, -1.2602],
        [ 0.7373, -1.2557],
        [ 0.0218, -1.1679],
        [ 1.0000, -0.7622],
        [-1.9832,  0.9997],
        [ 0.7603, -1.2797]])

tensor([[-0.5242],
        [-0.7788],
        [ 0.1463],
        [-0.1297],
        [ 3.2244],
        [-1.8154],
        [ 0.1188],
        [-0.0441],
        [ 2.1464],
        [-2.6765],
        [-1.2281],
        [-0.3478],
        [-2.1101],
        [ 0.4907],
        [ 2.3339],
        [ 0.9219],
        [ 2.9138],
        [-2.8580],
        [ 2.4005]])

In [22]:
data_arrays = (features, lables)
dataset = data.TensorDataset(*data_arrays)
dataset[0]
data_iter = data.DataLoader(dataset=dataset, batch_size=5, shuffle=True)

(tensor([-0.8330,  1.3084]), tensor([-0.5242]))

In [16]:
data_iter

In [18]:
dataset[1]

(tensor([-0.5681, -0.5442]), tensor([-0.1948]))

In [29]:
for X, y in data_iter:
    print("----")
    print(X)
    print(y)

----
tensor([[-0.8330,  1.3084],
        [-1.5275, -0.4477],
        [-0.4842, -0.7460],
        [-0.4412, -0.0936],
        [-0.1890, -1.2602]])
tensor([[-0.5242],
        [-2.1101],
        [-0.0441],
        [ 0.1188],
        [ 0.4907]])
----
tensor([[ 0.7603, -1.2797],
        [-1.9832,  0.9997],
        [ 0.0218, -1.1679],
        [-1.7279, -2.0894],
        [-1.4265,  0.5725]])
tensor([[ 2.4005],
        [-2.8580],
        [ 0.9219],
        [-2.6765],
        [-1.8154]])
----
tensor([[ 1.0000, -0.7622],
        [-0.8957,  0.3543],
        [-1.0675, -1.0780],
        [ 0.7373, -1.2557],
        [-0.4510,  0.4578]])
tensor([[ 2.9138],
        [-0.7788],
        [-1.2281],
        [ 2.3339],
        [ 0.1463]])
----
tensor([[ 0.5799,  0.0231],
        [-0.6760, -0.0595],
        [ 0.9881,  2.3124],
        [-0.5219, -0.8494]])
tensor([[ 2.1464],
        [-0.3478],
        [ 3.2244],
        [-0.1297]])


In [27]:
iter(data_iter)

In [36]:
from torch import nn
net = nn.Sequential(
    nn.Linear(2, 1) #两个输入一个输出
)

In [37]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

loss = nn.MSELoss()

tensor([[0.0106, 0.0006]])

tensor([0.])

In [38]:
net.parameters()

<generator object Module.parameters at 0x30f3c6970>

In [40]:
trainer = torch.optim.SGD(net.parameters(), lr = 0.03)

In [ ]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:

        l = loss(net(X), y) # 计算loss
        trainer.zero_grad() # 清空梯度
        l.backward() # 仅仅计算梯度
        trainer.step() # step()函数是执行预定步骤

    l = loss(net(features), lables)
    print(f"epoch {epoch+1}, loss{l:f}")

epoch 1, loss2.196440
epoch 2, loss1.582972
epoch 3, loss1.140675
